### ISSUE TITLE
Cant export

### ISSUE THREAD

**Issue by TopOPPsC** [Sollumz/Sollumz#1005]
if i try to export my project as an xml then its nothing in the folder and no error code is showing up why?

![Image](https://github.com/user-attachments/assets/54fe843e-2c02-4982-ab58-6663f59ac83e)

![Image](https://github.com/user-attachments/assets/9153fe35-8dcd-4588-b19f-0824a1a02d4b)

![Image](https://github.com/user-attachments/assets/b1309657-3045-4ee1-a5ec-1eb271496e3d)

**Comment by TopOPPsC** [comment]
okay i managed to export it but its a ytfp or something but i want it to be a YDR what am i doing wroooong

**Comment by ook3D** [comment]
This isn't a bug, use the discord help channels
