### ISSUE TITLE
Missing _SETUP_TIME flag on time archetype

### ISSUE THREAD

**Issue by Yoniromo** [Sollumz/Sollumz#1013]
### 🔍 Issue Description

Flag 24 - `16777216` is missing in time flag list. Timed archetypes created with sollumz won't work ingame. It's needed to set up the flag manualy
I'm using plebmaster flag generator tool to allow timed archetypes to works ingame

### 🛠️ Sollumz Version(s)

2.5.0

### 🖥️ Blender Version(s)

4.2.2 LTS

### 🔄 Reproduction steps

Create an asset in Blender, auto-create the time archetype and tick some hours in the time flag list.

### 🎯 Expected Result

The timed archetype is supposed to appear or disappear depending on time flag ticked 

### ⚠️ Current Result

Timed archetypes appears randomly

**Comment by alexguirre** [comment]
Added that flag as "Allow Swap While Visible". Time archetypes do work without this flag, but will only appear or disappear when not visible, when the player camera is facing away. With the flag enabled, they will appear or disappear even if visible.
