### ISSUE TITLE
Issue with Bus Handling After Exporting from Blender (Sollumz)

### ISSUE THREAD

**Issue by IRAKUNITA95** [Sollumz/Sollumz#1017]
### 🔍 Issue Description

Hello everyone,

I’m experiencing an issue with a bus model I imported into Blender. After importing the original model and exporting it back to the game using the Sollumz plugin, I find that the bus handles poorly in-game, as if something has changed, even though I made no modifications to the model itself.

Description of the Problem
Model Type: Bus
After importing the bus into Blender and exporting it back out without any alterations, the handling is significantly affected in the game. It drives poorly, as if there have been changes made to the vehicle's parameters.
Steps Taken
Imported the original bus model into Blender.
Exported it back to the game without making any changes.
Confirmed that all transformations were applied correctly before exporting.
Tested in-game, and the handling remains problematic.
Question
Does anyone have insights on what might cause this issue? Is there a specific setting in the Sollumz export process that could affect vehicle handling, even when no modifications are made?

Thank you for your assistance!

### 🛠️ Sollumz Version(s)

Latest

### 🖥️ Blender Version(s)

4.2.3

### 🔄 Reproduction steps

.

### 🎯 Expected Result

.

### ⚠️ Current Result

.

### 📎 Attachments

.

**Comment by alexguirre** [comment]
Hi, please try the latest commit.
