### ISSUE TITLE
Vehicle Handling Broken After Exporting from Blender (Bus Model) Sollumz

### ISSUE THREAD

**Issue by IRAKUNITA95** [Sollumz/Sollumz#1020]
### 🔍 Issue Description

Hello,

I'm experiencing an issue where simply importing a vehicle model's XML (exported from CodeWalker) into Blender and then exporting it without making any changes causes significant issues with the vehicle's handling in-game. Specifically, the vehicle I'm working on is a bus, and while it handled perfectly before any changes, after exporting from Blender, its handling is completely broken.

I have compared the XML generated by the Blender export with the original XML from CodeWalker, and I noticed several differences that might be causing the problem. However, even without altering anything in Blender, these changes occur, and the handling becomes noticeably worse.

### 🛠️ Sollumz Version(s)

2.4.2 latest commit 

### 🖥️ Blender Version(s)

4.2+

### 🔄 Reproduction steps

Export the vehicle XML from CodeWalker.
Import the XML into Blender using Sollumz.
Export the model from Blender without making any changes.
Replace the model in-game.

### 🎯 Expected Result

significant issues with the vehicle's handling in-game

### ⚠️ Current Result

its handling is completely broken.

### 📎 Attachments

.

**Comment by ook3D** [comment]
Why did you open the exact same issue as the one that was already closed? Read the reply on the original issue

**Comment by IRAKUNITA95** [comment]
Good evening, I saw, read, and did what I was told, but the error persists and hasn’t been resolved. I'm looking for another solution, and I couldn’t find one in the closed ticket, which is why I reopened it, hoping someone can help me, as I’ve been breaking my head over this for three days now.

**Comment by ook3D** [comment]
Did you download the latest commit and test it?

**Comment by IRAKUNITA95** [comment]
Yes, I deleted what I had in Blender and downloaded the ZIP again here from GitHub on the official Sollumz page, in the latest version.

**Comment by ook3D** [comment]
Yes that should work, I guess its not fixed then

**Comment by alexguirre** [comment]
> Is this the correct way to get the latest commits?

Use this Download ZIP option:
![Image](https://github.com/user-attachments/assets/d39a79a3-bc1e-47d4-a20f-1937d26f61d2)

Then check in the add-ons tab that you have the correct version:
![Image](https://github.com/user-attachments/assets/1eecab03-d5b7-4f95-a539-2e214a369c3a)

**Comment by IRAKUNITA95** [comment]
Yes, I did exactly as you're showing there. I can make a video, no problem.

**Comment by IRAKUNITA95** [comment]
https://youtu.be/OmCTQ5vpsVk video link

**Comment by alexguirre** [comment]
Ok, thought you were talking about the vanilla bus model (bus.yft), which now works fine. I can't do much without the broken models, can you the original .yft.xml?

**Comment by IRAKUNITA95** [comment]
https://files.fm/u/4uda9ce9yx LINK FOR DOWNLOAD ORIGINAL XML

**Comment by IRAKUNITA95** [comment]
hello alex you have any news about the issue? thx

**Comment by cpmodding** [comment]
Please load these vehicle files and tell us it's solved or you're encountering other problems[citiport.zip](https://github.com/user-attachments/files/17622791/citiport.zip)

**Comment by IRAKUNITA95** [comment]
Alright, I’ll take care of it when I get home. I’m at work.

**Comment by IRAKUNITA95** [comment]
Good evening @cpmodding . I've tested it, and yes, this car is much better; it's nothing like the other one. What could be the issue? Did I do something wrong?

**Comment by cpmodding** [comment]
Collision offsets are way too far, not sure it was like that in original vehicle, i don't have zmodeler to verify.

![Image](https://github.com/user-attachments/assets/ccbd0209-a0e8-4634-807a-7c60145d9ad4)

**Comment by IRAKUNITA95** [comment]
work's fine at least
