### ISSUE TITLE
wont load model

### ISSUE THREAD

**Issue by joejoe9257** [Sollumz/Sollumz#1022]
### 🔍 Issue Description

export my yft.xml file go to blender import into it loads in 6 ish seconds and nothing is there tried many models and same outcome blender 4.2.3 and newest release of sollumz 

### 🛠️ Sollumz Version(s)

2.5.0

### 🖥️ Blender Version(s)

4.2.3

### 🧩 Area

Fragments

### 🔄 Reproduction steps

anytime i try to import

### 🎯 Expected Result

help figuring it out 

### ⚠️ Current Result

just wont work

### 📎 Attachments

nothing shows

**Comment by ook3D** [comment]
do you have import as asset enabled?
