### ISSUE TITLE
Shape dropdown list is empty

### ISSUE THREAD

**Issue by Creature40** [Sollumz/Sollumz#1023]
### 🔍 Issue Description

"Shape" dropdown list is empty for collision models. In previous version it had some data![Image](https://github.com/user-attachments/assets/5d97c47f-7eef-4af1-9ab3-0e0c0b90ce63)

### 🛠️ Sollumz Version(s)

2.5

### 🖥️ Blender Version(s)

4.2.3

### 🧩 Area

Collisions

### 🔄 Reproduction steps

UI bug? no tata in list

### ⚠️ Current Result

UI bug? no tata in list

**Comment by alexguirre** [comment]
Nothing should be shown there for geometry bounds now. Should hide that panel in those cases.
Only on other bounds types it has to show something.
![Image](https://github.com/user-attachments/assets/69adac0a-bcd0-42c2-9e97-3185246d153a)
![Image](https://github.com/user-attachments/assets/65b6d211-aba8-407f-b0cb-70fbaa752568)
