### ISSUE TITLE
Files Refuse To Import

### ISSUE THREAD

**Issue by Anna-Spanner** [Sollumz/Sollumz#1025]
### 🔍 Issue Description

This could 100% be an issue on my side with either the files or Blender itself. In the file exploring section after selecting "Import" none of the files appear. When I disable the filter and force them to import it seems to skip them all as you can see by the below image showing the import time of 194 files.

![Image](https://github.com/user-attachments/assets/ff83e6da-cde8-42f3-a74c-4ad7324fe1e9)

### 🛠️ Sollumz Version(s)

2.5.0

### 🖥️ Blender Version(s)

4.2.1 LTS

### 🧩 Area

Navmesh

### 🔄 Reproduction steps

Please find attached one of the many files. Simply attempt to import the file. [prop_vesp_5_2_detec_b.zip](https://github.com/user-attachments/files/17681157/prop_vesp_5_2_detec_b.zip)

### 🎯 Expected Result

It is expected to import correctly

### ⚠️ Current Result

Its import gets skipped and still returns a success and no information or indication that something went wrong.

### 📎 Attachments

Relevent files already attached

**Comment by alexguirre** [comment]
You need CodeWalker to export them as XML first. Then, you import those XML files in Blender.

**Comment by Anna-Spanner** [comment]
Thats fair, thank you <3. I will do this now. This issue can be closed or deleted and I will make a new one if I have more issues
