### ISSUE TITLE
When exporting a .ydr file the model is transparent in Codewalker and OpenIV

### ISSUE THREAD

**Issue by Speleokid** [Sollumz/Sollumz#1033]
### 🔍 Issue Description

I followed a lot of tutorials about Sollumz step by step but when i export any mesh and I open it with Codewalker RPF explorer it's blank. If the mesh has a collision model embedded and I turn on show collisions in Codewalker it shows the model's collisions.

### 🛠️ Sollumz Version(s)

2.4.2

### 🖥️ Blender Version(s)

4.3

### 🧩 Area

Drawables, Archetypes

### 🔄 Reproduction steps

1) Convert the mesh to a Drawable object
2) Assign a material to the object with the plugin
3) Add the texture in the section on the right panel
4) Create YTYP file
5) export YTYP file
6) export with blender .ydr file

### 🎯 Expected Result

The result I expect is my mesh opened in Codewalker

### ⚠️ Current Result

My current result is a blank space in Codewalker when  I open it

### 📎 Attachments

![Image](https://github.com/user-attachments/assets/cbbedb14-4b0d-443f-8562-68ffc670ec17)
![Image](https://github.com/user-attachments/assets/52b1f9bb-0ddf-40af-9b15-3ca7d7fef307)

**Comment by ook3D** [comment]
Make sure UVmap is named "UVMap 0" and it has vertex colours

**Comment by Speleokid** [comment]
> Make sure UVmap is named "UVMap 0" and it has vertex colours

What are vertex colours? I just renamed the UVMap to "UVMap 0" and it still doesn't work.

**Comment by ook3D** [comment]
> > Make sure UVmap is named "UVMap 0" and it has vertex colours
> 
> What are vertex colours? I just renamed the UVMap to "UVMap 0" and it still doesn't work.

Colour attributes tab

**Comment by Speleokid** [comment]
> > > Make sure UVmap is named "UVMap 0" and it has vertex colours
> > 
> > 
> > What are vertex colours? I just renamed the UVMap to "UVMap 0" and it still doesn't work.
> 
> Colour attributes tab

I don't actually found the tab you are saying...

**Comment by Speleokid** [comment]
![Image](https://github.com/user-attachments/assets/e796e23d-0746-4c35-ac3e-03464be0003b)
I just added also color attributes and still doesn't work

**Comment by Speleokid** [comment]
Thank you very much for the help I just solved the problem. It was a problem of hierarchy.

**Comment by Speleokid** [comment]
Thank you very much for the help I just solved the problem. It was a problem of hierarchy.
