### ISSUE TITLE
Incorrect display of the TintPaletteSample after the commit ab3791e

### ISSUE THREAD

**Issue by MaaximGL** [Sollumz/Sollumz#1034]
### 🔍 Issue Description

This is a reopening of the issue #1029 . Because the previous one was closed with a commit punch that was still not correct.

The message was sent to a closed pull request #1030 , but I decided because it is closed, I will publish it in an open topic. The mathematically correct solution does not work in a blender, the rounding that was previously discussed and that I proposed does not work.

I uploaded the commit  and it doesn't seem to work correctly.
Pixel "146" disappears.
1st line - last commit of the repository.
2nd line - rounding to 0.004

### 🛠️ Sollumz Version(s)

dev commit ab3791e

### 🖥️ Blender Version(s)

4.2

### 🧩 Area

Shaders

### 🔄 Reproduction steps

1. Create a palette.
2. Paint the polygons according to the palette using the blue vertex channel
(0/255, 1/255, 2/255, 3/255, ...).
3. Export the model to CW Rpf to ensure the palette works correctly (the difference in painted areas for bits 146 will be noticeable (in Blender and in Rpf)).

### 🎯 Expected Result

Expected behavior:
The blue ch. at 145/255 in the vertex group in the model takes the 146 px value instead of 145;
and now all the subsequent ones are shifted by 1.

### ⚠️ Current Result

You won't see these colors correctly in Blender, but if you look at the model in CW Rpf, everything will work as expected.

### 📎 Attachments

[test_pal.zip](https://github.com/user-attachments/files/17789389/test_pal.zip)
2 nodes, 2 meshes, texture 4x256 pixels
![Image](https://github.com/user-attachments/assets/e57f64b5-ad0e-4dce-b858-99b89a0bb655)

**Comment by alexguirre** [comment]
It was later replaced with your proposed solution of using 0.004. Is it still causing issues? https://github.com/Sollumz/Sollumz/commit/8a6d87c7a52f95ed494517cacbcd4e43f4c7a5d4

**Comment by alexguirre** [comment]
I see I forgot to mention the new commit in the PR, my bad.

**Comment by MaaximGL** [comment]
I'll check it out today. And I'll let you know in this thread.

**Comment by MaaximGL** [comment]
Great, it works as it should.
