### ISSUE TITLE
[MLO Ytyp] huge lag with portal filter

### ISSUE THREAD

**Issue by MiniBulle3D** [Sollumz/Sollumz#1036]
### 🔍 Issue Description

Hello,

i have a MLO with 15 portals. If i clic on the mlo archetype => Entites => Filter by portal  : i have huge lags.
Everything is ok if i use "Room" filter or "All" filter.
If i do the same thing with a mlo ytyp with 5 portals everything is ok too. It seems to be due to the number of portal.

PS : i had the same issue with sollumz 2.4 & blender 4.1, i updated to sollumz 2.6 to see if it can solve the issue.
Also, note that this project has been made with sollumz 2.4 & blender 4.1.

Let me know if you need more information.

Thanks a lot for your help !

### 🛠️ Sollumz Version(s)

2.6

### 🖥️ Blender Version(s)

4.2.4

### 🧩 Area

Archetypes

### 🔄 Reproduction steps

![Image](https://github.com/user-attachments/assets/3d1440c8-9304-4d68-9a6f-969a021b78f9)

### ⚠️ Current Result

Huge lags

**Comment by alexguirre** [comment]
Yes, same issue as reported here https://github.com/Sollumz/Sollumz/issues/801.
