### ISSUE TITLE
Can't get over a prop creation. Texture not correctly applying, however it correctly displays in Blender

### ISSUE THREAD

**Issue by Ninovui** [Sollumz/Sollumz#1048]
### 🔍 Issue Description

Hello !
It's been time since I'm trying to create props for police operation. However, I can't get over it's creation, the texture is always missing in the ydr file, no matter what I'm trying...

Here's what's possible screenshot so maybe someone can help me get over it...

how it is supposed to look like :
![Image](https://github.com/user-attachments/assets/545c2ee2-cb8f-4c4c-bec0-bf7007885b26)

here's some config screenshots :
![Image](https://github.com/user-attachments/assets/beda6245-6e7b-433b-aa8e-32991c8f571e)

![Image](https://github.com/user-attachments/assets/a2a6228a-b25d-4315-a4fa-de3e3a086375)

![Image](https://github.com/user-attachments/assets/7c5499ae-476d-427b-9335-6d1fb52e23a5)

![Image](https://github.com/user-attachments/assets/cfda5da9-f64d-4764-b1bd-a607a6db090a)

![Image](https://github.com/user-attachments/assets/a2686257-eeea-4c76-81e5-a982732a651c)

The final rendu on CodeWalker :
![Image](https://github.com/user-attachments/assets/bcfc2631-db28-43c1-a676-beefffd38b92)

![Image](https://github.com/user-attachments/assets/ff0d6657-3a37-49a2-9683-bbecd8b5e976)
--> Notice the error at the bottom of the window. I found nothing on the internet regarding that kind of error...

Thank you for your help !

### 🛠️ Sollumz Version(s)

2.4.1

### 🖥️ Blender Version(s)

4.1

### 🧩 Area

Drawables

### 🔄 Reproduction steps

Followed youtube tutorials to make it work but nothing here...

### 🎯 Expected Result

![Image](https://github.com/user-attachments/assets/545c2ee2-cb8f-4c4c-bec0-bf7007885b26)

### ⚠️ Current Result

![Image](https://github.com/user-attachments/assets/bcfc2631-db28-43c1-a676-beefffd38b92)

**Comment by ook3D** [comment]
this is not a bug, your texture resolution is not power of 2, please use the discord help channels
