### ISSUE TITLE
Refactor shader node setup

### ISSUE THREAD

**Issue by ook3D** [Sollumz/Sollumz#747]
Preferably using a blend file shipped with sollumz and each shader node layout and nodes already setup using custom node groups

**Comment by alexguirre** [comment]
Some ongoing work in [`dev/shader-expressions`](https://github.com/Skylumz/Sollumz/tree/dev/shader-expressions) branch. The aim is to define shaders by building a kind of AST through normal python expressions and function calls that somewhat resemble a shading language. Then this AST can be "compiled" to a shader node tree. This should simplify editing existing shaders and creating new ones as we would not have to care about manually creating nodes and linking them, which takes a lot of code for what is in reality very simple shader code.

Another benefit is that the shader definitions would stay as plain-text code, simple to version control compared to a binary .blend file.

**Comment by alexguirre** [comment]
`dev/shader-expressions` is merged now. Most materials still don't use it but we will be slowly migrating them (#1007, 124350d3a632258a8336370bfa5dd3aa85790898, dev/ynv-qol branch, etc.). Any new material generation code should be using shader expressions from now on.
