### ISSUE TITLE
Vehicles: Wheels broken when export

### ISSUE THREAD

**Issue by FilipeCuco** [Sollumz/Sollumz#860]
When I export any car the wheels are all crooked
![image](https://github.com/Skylumz/Sollumz/assets/116587926/98e3317a-9b70-4f76-ab61-2a4e8d8f5b76)

**Comment by alexguirre** [comment]
Started with this commit 2a079c5abfd9960f1126462aead43671a941ef53.

**Comment by alexguirre** [comment]
Seems to work fine in-game though.
![image](https://github.com/Skylumz/Sollumz/assets/12873137/c1fe1a54-f9ae-4279-96d7-e06a19fdefb6)

**Comment by alexguirre** [comment]
Yeah, the fix in 2a079c5abfd9960f1126462aead43671a941ef53 was to solve some incorrect physics in YFTs. For the props and vehicles I tested it calculated the same values as the original, but for this T20 model they are slightly different, the game seems to still be fine with them but CW not so much.

**Comment by FilipeCuco** [comment]
> Yeah, the fix in [2a079c5](https://github.com/Skylumz/Sollumz/commit/2a079c5abfd9960f1126462aead43671a941ef53) (part of 2.4.0) was to solve some incorrect physics in YFTs. For the props and vehicles I tested it calculated the same values as the original, but for this T20 model they are slightly different, the game seems to still be fine with them but CW not so much.

I just imported and exported the model, you can see that the position of the wheels in codewalker leaves a larger opening and this happens with all models

police3 Vanilla Model:
![image](https://github.com/Skylumz/Sollumz/assets/116587926/cad2701a-10d6-40df-ab86-2ca84c67b32e)

police3 Exported Model:
![image](https://github.com/Skylumz/Sollumz/assets/116587926/c07d1a28-5f1e-43e9-88bc-3d89143f5f2e)

**Comment by VolpeDelDeserto** [comment]
This issues is still present. Wheels are in the wrong position after import -> export

**Comment by ook3D** [comment]
> This issues is still present. Wheels are in the wrong position after import -> export

thats why the issue is still open, lol
