### ISSUE TITLE
i can't export animation [sollumz dev-anim-mover]

### ISSUE THREAD

**Issue by otakustam1150** [Sollumz/Sollumz#902]
![image](https://github.com/Skylumz/Sollumz/assets/41570656/16d7fd93-5aa5-48e3-8860-7b3068ce9f38)
i don't know what issue 
my blender version 4.1.1

**Comment by ook3D** [comment]
bruh you are using a development branch of sollumz and wondering why it doesnt work

**Comment by Drenchanim** [comment]
> bruh you are using a development branch of sollumz and wondering why it doesnt work

i have the same problem wym the development branch of sollumz

**Comment by Rover123456** [comment]
i have it too
