### ISSUE TITLE
Vehicle Paint Layer setting is not applied/saved while exporting a vehicle

### ISSUE THREAD

**Issue by Reldam88** [Sollumz/Sollumz#922]
Blender v4.1.1
Sollumz v2.4.2

After trying and failing to make a vehicle interior paintable, I re-imported it with Sollumz and found that the Paint Layer setting under the Fragment tab was set to [Not Paintable] after I had already changed it to [Secondary] and exported.

In order to confirm that Sollumz is bugged, I imported the vehicle into ZModeler3, set the same material paint layer to [Secondary] and the interior successfully changed color in-game.
![2024-06-25_15-25-59](https://github.com/Skylumz/Sollumz/assets/161262221/37ba436b-fd38-4a11-936b-6f3f455ffc83)

**Comment by Dk0071942** [comment]
Actually, I believe there is nothing wrong with the code. You should go to the outliner panel, data and check which lod level you edit. Make sure that you change the material of the mesh under the level "high". To be 100% percent on the safe side, just do it for all level. It took me a day to figure that out.

**Comment by Reldam88** [comment]
Thank you for the suggestion. This is a custom vehicle that has only a single LOD level (Very_High) because I haven't created the lower LODs for it yet. So it's literally impossible that I'm applying changes to the wrong LOD.

I also verified that the material will be linked between LODs, so any Paint Layer change would automatically apply to all of them.

I always leave LOD creation to last. Otherwise, any changes that are made to a Very_High LOD won't appear in the lower LODs and the vehicle will magically transform as the player walks away from it.

**Comment by Dk0071942** [comment]
What I am gonna to say may not be 100% correct because it is purely based on my experience and assumption. The yft contains 4 LOD level info and the _hi.yft contains only one level info. If you only import the _hi.yft and leave the yft unchanged, it could cause you even more errors and bugs. The correct way should be either import yft only or click the option import with _hi. But in general, you should always import the yft without hi only. After the editing, export the file, copy it and rename the copy to _hi. This should solve your issue. :)

**Comment by Dk0071942** [comment]
So in general, stick with the yft file and the LOD level high and use the level high to create other levels of LOD. The LOD level very high can just be a copy of the level high and the game engine takes the level high as the main level.

**Comment by Reldam88** [comment]
Well it sure sounds like the paint layers aren't causing you any problems. So now you got me second guessing myself and I'm gonna go back and make sure I'm setting up my LODs correctly. I appreciate all the info!
