### ISSUE TITLE
Exporting To Codewalker XML Not Actually Exporting

### ISSUE THREAD

**Issue by Wthiscrz** [Sollumz/Sollumz#937]
Ok, so I debadge cars and I have not previously had any issues with the plugin before, however now when I go to export it (with the file selected and exporting through the sollumz menu) it will take about 5 seconds and say at the bottom that it has exported (see image below) 
![image](https://github.com/user-attachments/assets/997aecba-d00e-4ae2-b90c-bf387ffd59c3)
however when I check the export folder, it is empty 
![image](https://github.com/user-attachments/assets/4ab121ce-6ef4-415d-a0e4-bf65c46fd045)

**Comment by ook3D** [comment]
It clearly exported, as the time is not 0, also why are you even "debadging" cars, it's literally a waste of time, it's still against fivems terns of service, only thing you are accomplishing is wasting your own time

**Comment by Wthiscrz** [comment]
first off, it hasnt exported as there is no file in the folder i specified for the file to export to, secondly, the copyright law from fivem from what i understand only truly occurs to people in the US, and as i am not from or reside in the US, I do in fact believe that I am immune in a sense to this issue.

**Comment by ook3D** [comment]
> first off, it hasnt exported as there is no file in the folder i specified for the file to export to, secondly, the copyright law from fivem from what i understand only truly occurs to people in the US, and as i am not from or reside in the US, I do in fact believe that I am immune in a sense to this issue.

Thats not how it works, it's not about the actual law, it's about the platform rules.

**Comment by Wthiscrz** [comment]
well either way could i know if there is a reason why it isnt properly exporting?

**Comment by alexguirre** [comment]
If you click on the "Exported in x seconds" message, it should open the log window. Check if there is any error before the last message.
