### ISSUE TITLE
I got a error when importing a .ydr file

### ISSUE THREAD

**Issue by JIMXGtamods** [Sollumz/Sollumz#940]
I cannot importing .ydr file cause i have nearly-always this error.
![image](https://github.com/user-attachments/assets/4f00d5f9-35a9-4798-b4e3-1df71972dc50)

**Comment by ook3D** [comment]
You need to update sollumz from git, not latest release, if you plan to use 4.2

**Comment by JIMXGtamods** [comment]
Sorry but how to do that?

**Comment by JIMXGtamods** [comment]
Ok thanks for the fast reply, i didn't notice xd!
I have update to source code one and it's working thank you!!!
