### ISSUE TITLE
error does not matter

### ISSUE THREAD

**Issue by ytbgemer** [Sollumz/Sollumz#941]
Hello, I'm Brazilian, I'm having problems with the following message (no sollumz objects selected for export), what could it be? I select everything correctly but it always happens, I used Google Translate so if I get something written wrong!
![AA (1570)](https://github.com/user-attachments/assets/b4939b1c-ac42-4a77-8e12-3e771e56557c)

**Comment by ook3D** [comment]
Your hierarchy is completely incorrect.

**Comment by ytbgemer** [comment]
but I did it exactly like this in a guy's video on YouTube, and his work worked, I'll try to do it again

**Comment by TopOPPsC** [comment]
why yall closing this i got the same issue and i bet many people too

**Comment by ytbgemer** [comment]
Well, I've seen several videos and none of them managed to fix this error.
