### ISSUE TITLE
Extent YMAP not kept in data

### ISSUE THREAD

**Issue by Gusepe** [Sollumz/Sollumz#944]
1. Extents & Streaming extents entities don't seem to be saved as data when imported into blender. This gives a false result when exporting, and forces you to run each YMAP through codewalker again just to calculate the extents.

 It would therefore be interesting to save the extents of a YMAP where the extents are already calculated.

2. Add an auto-calculation option when exporting?

3. We could also consider a box allowing us to manually fill in our extents (previously calculated on CW) with a C/C

![image](https://github.com/user-attachments/assets/42a89a1a-33ae-4193-b94e-0f223bc99517)

**Comment by alexguirre** [comment]
Yeah, someone reported this before but didn't open an issue. So Sollumz is supposed to calculate the extents on export but for some reason it only takes the occluders into account, which is completely wrong.
![image](https://github.com/user-attachments/assets/2357d669-c31c-46b0-a7fd-acb2cfecdcb2)

**Comment by Gusepe** [comment]
@alexguirre 

There are certain cases where it's interesting not to recalculate the extents.

**Example:**

To easily modify an area, I want to remove a building, I put it far below the map (-1000), if I recalculate the extents, this will be recalculated to -1000. The in-game impact doesn't exist or very little, but it will be cleaner to keep the basic extent without recalculating it.
