### ISSUE TITLE
Add a confirmation dialog when exporting without uv map

### ISSUE THREAD

**Issue by krzysiula3000** [Sollumz/Sollumz#952]
or a notification, also when the uv map is empty / not named properly with the index

**Comment by alexguirre** [comment]
Now there are warnings in the UV maps and color attributes panels, but I guess a warning on export would be good too.
![image](https://github.com/user-attachments/assets/7cbaccf1-660b-4ddd-88d7-b57a08ffd969)

**Comment by krzysiula3000** [comment]
yea i noticed that and it's a v good change, however there is still so much stuff like that, giving exception errors and confusing people instead of actually being helpful describing what could've went wrong. 
For example, selecting an action with no keyframes in the ycd gives an exception error, instead of checking for that and giving an appropriate message like "no keyframes in the action" which would be 10000x more helpful and if the person had at least a braincell they would likely figure it out, eliminating the need to ask in the discord and wait for a response

**Comment by alexguirre** [comment]
Yes, it should never show exception errors without a clear message. Just open a new issue when encountering those cases.
