### ISSUE TITLE
YFTs Not Importing Into Blender

### ISSUE THREAD

**Issue by LIPDProductionsInc** [Sollumz/Sollumz#960]
When I attempt to input a YFT.xml into Blender, it says it's imported, but no model appears. I have attempted to reinstall the plugin as well as reset any settings I may have accidentally changed, but I still can't get any YFTs imported. Any advice?

**Comment by ook3D** [comment]
disable import as asset

**Comment by LIPDProductionsInc** [comment]
I'm mad at how simple that was. Thank you
