### ISSUE TITLE
Adding a shader material to a drawable gives an exception error

### ISSUE THREAD

**Issue by krzysiula3000** [Sollumz/Sollumz#961]
when you try to add it to a drawable instead of a drawable model

**Comment by Rigonkmalk** [comment]
wdym about Adding a shader material to a drawable ?

You mean in your empty ? or your mesh ?
Does the Sollumz Type of the mesh is "Drawable model" ?

**Comment by krzysiula3000** [comment]
i mean the drawable object, the empty
yes

instead of asking you could test it instead and not wait 6h lol

![2024-08-27_19-14](https://github.com/user-attachments/assets/f83efe8c-f136-42c7-9ec0-7d01d578cbd0)

![2024-08-27_19-14_1](https://github.com/user-attachments/assets/579da3c6-721f-4d0e-bc67-cd820f8943e8)
![2024-08-27_19-14_2](https://github.com/user-attachments/assets/001c56ec-b6fd-4e15-9f7a-5058fb870b8a)

**Comment by Rigonkmalk** [comment]
![image](https://github.com/user-attachments/assets/0d70726d-1231-4ff7-86e2-6a8fe66a1845)

Reproduced on last `main` commit
