### ISSUE TITLE
Panning the camera is blocked when hovering over lights

### ISSUE THREAD

**Issue by krzysiula3000** [Sollumz/Sollumz#966]
Not only panning but other stuff such as inverting selection, tp to object (numpad del), moving, and probably many others, the new light gizmos are buggy in general

https://streamable.com/8ot3xr

**Comment by krzysiula3000** [comment]
that link expires in 2 days btw

**Comment by alexguirre** [comment]
https://github.com/user-attachments/assets/b4653da5-6f9d-4bc4-8365-8ab0f7bcbea9
