### ISSUE TITLE
importing xml files for gta cars error

### ISSUE THREAD

**Issue by Beemo530** [Sollumz/Sollumz#968]
## Description

< When I try to import a car model, I get an error.
![error blender](https://github.com/user-attachments/assets/e9eeb4cd-e31c-473a-a941-ad48301f318b)
>

## Steps to reproduce

<use code walker to convert files to xml
open blender
import codewalk
error shows
hide collisions
no car model>

## Actual result

< 
![image](https://github.com/user-attachments/assets/c1cb3f02-ccfa-49bc-ad9d-708ab70a4da1)
 >

## Expected result

< car model>

## Additional context

<trying to modify exsisting car models for gta >

**Comment by ook3D** [comment]
update sollumz to the latest commit if you are going to use blender 4.2
