### ISSUE TITLE
Add import option to ignore bounds (ydr)

### ISSUE THREAD

**Issue by ook3D** [Sollumz/Sollumz#970]
## Description

< What would you like to add as a new feature? >
New import option checkbox to exclude / ignore bounds inside drawables, this would be useful for when you are importing lets say a full interior simply just to take some renders of it, or an area of the map, you would need to either delete all collision objects or toggle their render visibility.

## Explanations

< Please explain how it would work >
Check if the import setting is enabled, if it is, skip importing the bounds of the drawable

## Attachments

< Please upload examples, if there is any >

**Comment by alexguirre** [comment]
I feel like this will just end up with more people asking for help, "Import as asset" already causes enough issues. Somehow people end up randomly toggling import options.

**Comment by ook3D** [comment]
> I feel like this will just end up with more people asking for help, "Import as asset" already causes enough issues. Somehow people end up randomly toggling import options.

i agree, maybe we can add like "advanced options" in preferences and add a warning or 2 to say, do not touch this if you are not experienced
