### ISSUE TITLE
I'm trying to import the build texture and showing this and when I try to import building to blender show this

### ISSUE THREAD

**Issue by SWEz11** [Sollumz/Sollumz#973]
When I try to Import the building it shows this error: 
![image](https://github.com/user-attachments/assets/e6179fb2-3250-4c93-83f4-eb8ffcd55cc1)
it show not much texture of the building:
![image](https://github.com/user-attachments/assets/a1a0dcda-6c6a-4633-afaf-c16fb237760d)
But when I try to import building texture it shows this error: 
![image](https://github.com/user-attachments/assets/bfa831d9-f50d-4874-8157-6258a44e2cae)
![image](https://github.com/user-attachments/assets/2ac22d31-8a30-4fce-b71b-c56ffc8b29b3)
My blender versions is 4.2.1
The Sollumz version is the lastest version

**Comment by ook3D** [comment]
this isnt a bug, use the proper help channels in discord.

**Comment by SWEz11** [comment]
> this isnt a bug, use the proper help channels in discord.

already do that but now the all textures load but some things not
![image](https://github.com/user-attachments/assets/35d9dcc6-2f8e-443c-b4dd-38c22d0daf46)
