### ISSUE TITLE
Texture not loading

### ISSUE THREAD

**Issue by xWyll** [Sollumz/Sollumz#975]
Hello,
Ive made the skin in PS and imported it as a DDS file but when I link it in the texture parameters the gun remains black, not sure what I have missed. Hoping someone is able to help out. Thanks

![image](https://github.com/user-attachments/assets/452a731a-2f77-486e-8155-81b5bbedad10)

![image](https://github.com/user-attachments/assets/e79d8c01-1684-4638-b956-22b7503b5beb)

**Comment by ook3D** [comment]
this is not a sollumz bug
