### ISSUE TITLE
UV scale crush

### ISSUE THREAD

**Issue by Creature40** [Sollumz/Sollumz#987]
### 🔍 Issue Description

Working with different car models(downloaded from web), I found that after some time of work, saving and opening file, scaling UV map messes it up and/or can cause Blender to crush. This can occur with both existing UV or freshly unwrapped. Doing the same with plugin turned off works as expected. The issue can be fixed by exporting file to XML and importing it back to Blender.
![unwrapped_UV](https://github.com/user-attachments/assets/96c0ea3f-d3ea-4082-ac89-1e20e50bc7a3)
![Scaled_UV](https://github.com/user-attachments/assets/96636b00-4dc2-416e-b390-316841782842)
![problematic part example](https://github.com/user-attachments/assets/e453cb5f-ca51-4297-937e-eeb0a417121d)
[m3Touring.zip](https://github.com/user-attachments/files/17235295/m3Touring.zip)
[xml.zip](https://github.com/user-attachments/files/17235282/xml.zip)
Check the attached files. there is different parts in it cause the same issue. This is not only model I have same problem with.

### 🛠️ Sollumz Version(s)

2.4.2

### 🖥️ Blender Version(s)

4.2.2

### 🔄 Reproduction steps

select any part of the model and try to scale it's UV or unwrap and scale

### 🎯 Expected Result

scaling UV map messes it up and/or can cause Blender to crush

### ⚠️ Current Result

scaling UV map messes it up and/or can cause Blender to crush

**Comment by ook3D** [comment]
Really not sure how this could be the fault of sollumz, I've never had this issue and been using sollumz daily for almost 3 years now, could you send the blend file? I'm assuming it's  another addon of yours or something crashing you

**Comment by Creature40** [comment]
I had attached the blend file already, but no problem here is another one with same issue.
[camaro.zip](https://github.com/user-attachments/files/17269429/camaro.zip)

![image](https://github.com/user-attachments/assets/7abdba6b-7698-4f7a-84b8-b700045ff6da)
As I described, the issue does not appear if the problematic file opened **without** sollumz add-on enabled. Also, I don't use any other third-party add-ons
![image](https://github.com/user-attachments/assets/9d1f4aca-cb91-4864-8cc1-7d4bbb924dca)

**Comment by Creature40** [comment]
Also, I tried to open those files on different PC with freshly installed Blender 4.2.2 and Sollumz plugin 2.4.2. Unfortunately, the issue still there.

**Comment by alexguirre** [comment]
Was able to reproduce the crash on Blender 4.2 and Sollumz 2.5.

Blender console output:
```
Memoryblock mempool chunk: error in header
Saved session recovery to "C:\Users\ALEXGU~1\AppData\Local\Temp\quit.blend"
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0xFFFFFFFFFFFFFFFF
Module  :
Thread  : 00025d64
Writing: C:\Users\ALEXGU~1\AppData\Local\Temp\camaro.crash.txt
```

Crash log: [camaro.crash.txt](https://github.com/user-attachments/files/17447163/camaro.crash.txt)

Interesting bits:
```
Stack trace:
blender.exe         :0x00007FF6CB459880  check_memlist
blender.exe         :0x00007FF6CB459F40  MEM_guarded_freeN
blender.exe         :0x00007FF6CB3D3FF0  BLI_mempool_free
blender.exe         :0x00007FF6CB121270  CustomData_bmesh_free_block
blender.exe         :0x00007FF6CB530DC0  update_data_blocks
blender.exe         :0x00007FF6CB52DE90  BM_data_layer_add
blender.exe         :0x00007FF6CB972FE0  BPy_BMLoop_CreatePyObject
python311.dll       :0x00007FFADDEB9EE0  PyEval_EvalFrameDefault
python311.dll       :0x00007FFADDEB9EE0  PyEval_EvalFrameDefault
python311.dll       :0x00007FFADDD94F90  PyFunction_Vectorcall
python311.dll       :0x00007FFADDD94B90  PyVectorcall_Function
python311.dll       :0x00007FFADDD94DE0  PyObject_Call
blender.exe         :0x00007FF6CB953EC0  bpy_prop_int_get_fn
blender.exe         :0x00007FF6CB9614C0  pyrna_prop_to_py
blender.exe         :0x00007FF6CB958290  pyrna_struct_getattro
python311.dll       :0x00007FFADDDDF860  PyObject_GetAttr
python311.dll       :0x00007FFADDEB9EE0  PyEval_EvalFrameDefault
python311.dll       :0x00007FFADDEB9EE0  PyEval_EvalFrameDefault
python311.dll       :0x00007FFADDD94F90  PyFunction_Vectorcall
python311.dll       :0x00007FFADDD94B90  PyVectorcall_Function
python311.dll       :0x00007FFADDD94DE0  PyObject_Call
blender.exe         :0x00007FF6CB95BBC0  bpy_class_call
blender.exe         :0x00007FF6CB8EFBA0  panel_draw

...

# Python backtrace
  File "...\yft\properties.py", line 161 in get_light_id_of_selection
  File "...\yft\ui.py", line 132 in draw
```
Seems we are doing something wrong when accessing the mesh in `get_light_id_of_selection`.

**Comment by alexguirre** [comment]
If you close the "Vehicle Light IDs" panel it doesn't crash.

**Comment by Creature40** [comment]
Oh yes, with lights panel closed it does not crash. Thank you!
