### ISSUE TITLE
Favorite system for shaders list

### ISSUE THREAD

**Issue by alexguirre** [Sollumz/Sollumz#990]
### 📝 Feature Description

Allow to tag specific shaders as favorites, then filter them to only show favorites.

### 🔧 Feature Workflow

- Add a "favorite" toggle button on each entry on the list.
- Add a checkbox to show favorites only in the filtering options below the shaders list, where the search box is.
- The favorites are saved in the user preferences.

**Comment by SaifAlDilaimi** [comment]
+1
