### ISSUE TITLE
Materials / Invalid settings for car color parameter

### ISSUE THREAD

**Issue by cpmodding** [Sollumz/Sollumz#997]
### 🔍 Issue Description

When creating a new material for car paint (vehicle_paint_1 to _9) and changing Paint Layer from dropdown in Fragment options, values in **matDiffuseColor** parameter aren't set properly. Values are set for the primary vehicle color. The very same issue happens for already created material.

Correct values are:
matDiffuseColor for primary paint - 2.0, 1.0, 1.0
matDiffuseColor for secondary paint - 2.0, 2.0, 2.0
matDiffuseColor for wheel color - 2.0, 4.0, 4.0
matDiffuseColor for interior trim - 2.0, 6.0, 6.0
matDiffuseColor for dashboard color - 2.0, 7.0, 7.0

### 🛠️ Sollumz Version(s)

latest commit

### 🖥️ Blender Version(s)

4.2

### 🔄 Reproduction steps

As on the video.

New material:
https://github.com/user-attachments/assets/08c2dc4d-db78-487b-b138-446ee369ad97

Existing material from import
https://github.com/user-attachments/assets/b3f4b361-6b65-44de-98be-fa37ba8c86e2

### 🎯 Expected Result

After changing the option in Paint Layer dropdown, matDiffuseColor should be set to proper values, depending on chosen color.

### ⚠️ Current Result

matDiffuseColor values are permamently set to primary car paint.

**Comment by alexguirre** [comment]
That's actually kinda the expected behavior at the moment. The parameter is overwritten when doing the export, not when setting the dropdown.
https://github.com/Sollumz/Sollumz/blob/a7e5cab205b2e2d47635b6ae9a2f0ecbde5cd3cb/yft/yftexport.py#L121-L133

But yeah, I agree it can be confusing and the dropdown should use the parameter instead of its own separate thing.

**Comment by cpmodding** [comment]
Sadly, i can't confirm that. Just moment ago, i've changed the color for paint material to Dashboard (and changed the diffuse texture to find it easier in xml).

https://github.com/user-attachments/assets/382f7af9-3d2a-49ed-955a-f7cd166feaf0

though this code above doesn't reflect into the XML.
![Image](https://github.com/user-attachments/assets/2fa94dff-a909-41fe-995f-b957169074e9)

**Comment by alexguirre** [comment]
Interesting, the parameter is only overwritten on the non-hi yft file.
![Image](https://github.com/user-attachments/assets/09781963-ad7e-4ac4-8a49-3d74fbe3da84)

Tested on Sollumz 2.0, and it also has this bug, so it had always been broken 🙃. Though, afaik, people got vehicle paint working with Sollumz, the game might only be checking the non-hi shader parameters.

But yeah, this is not intended.
