### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by ZgreDziu** [Sollumz/Sollumz#998]
### 🔍 Issue Description

Hey, yesterday I've opened Blender and imported my .ydr file. But apart from information "succesfully imported" nothing showed up in hierarchy. After that I reinstalled blender and did some things but it didn't help. In the morning everything was working correct. Only .ybn files are importing. 

### 🛠️ Sollumz Version(s)

2.5 (latest)

### 🖥️ Blender Version(s)

4.2.3LTS

### 🔄 Reproduction steps

Install blender 4.2.3LTS, install the newest Sollumz, Try import .ydr file.

### 🎯 Expected Result

Possibility to import .ydr files again

### ⚠️ Current Result

Annoucement "Successfully Imported" and that's all.

### 📎 Attachments

![Image](https://github.com/user-attachments/assets/49998d56-da19-4fb4-94fa-400365a71410)

**Comment by ook3D** [comment]
Disable import as asset checkbox.

**Comment by ZgreDziu** [comment]
And really that was all... sometimes I feel really dumb for asking about that easy things. Really thank you. Have a nice day !
